Catalogue.create!([
  {name: "GC - Hardware", description: nil},
  {name: "GC - Software", description: nil},
  {name: "Capital", description: nil},
  {name: "Essential", description: nil},
  {name: "Eutectic", description: nil},
  {name: "PPOMX - Proveedores", description: nil},
  {name: "GC - Punto de Venta", description: nil},
  {name: "GC - Comunicaciones", description: nil},
  {name: "Hardware", description: nil},
  {name: "Befective", description: nil},
  {name: "PPOMX - Change Requests", description: nil},
  {name: "Comunicaciones", description: nil},
  {name: "Aplicaciones", description: nil},
  {name: "Software", description: nil},
  {name: "Accesos", description: nil},
  {name: "Statistics", description: nil},
  {name: "Access", description: nil},
  {name: "Teams & Teammates", description: nil},
  {name: "Download", description: nil},
  {name: "Payment", description: nil},
  {name: "GC - Telefon�_a", description: nil},
  {name: "Self Service", description: nil},
  {name: "itManager  - PPO - Interno", description: nil},
  {name: "Suggestions & Complains", description: nil},
  {name: "ANGLO", description: nil},
  {name: "Administration", description: nil},
  {name: "ControlCambio", description: nil},
  {name: "Perfil", description: nil},
  {name: "Empresa", description: nil},
  {name: "Equipos y Colegas", description: nil},
  {name: "Agente", description: nil},
  {name: "Estadisticas", description: nil},
  {name: "Sugerencias", description: nil},
  {name: "LOLO", description: nil},
  {name: "Administradores y Rerentes", description: "some"}
])
Area.create!([
  {name: "CPU", catalogue_id: 1, description: nil},
  {name: "Perifericos", catalogue_id: 1, description: nil},
  {name: "Windows", catalogue_id: 2, description: nil},
  {name: "Applications", catalogue_id: 3, description: nil},
  {name: "Networking", catalogue_id: 3, description: nil},
  {name: "Assessment", catalogue_id: 3, description: nil},
  {name: "Hardware", catalogue_id: 3, description: nil},
  {name: "Red", catalogue_id: 4, description: nil},
  {name: "Aplicaciones", catalogue_id: 4, description: nil},
  {name: "Sistema Operativo", catalogue_id: 4, description: nil},
  {name: "Applicatons", catalogue_id: 5, description: nil},
  {name: "Servicios", catalogue_id: 6, description: nil},
  {name: "Fabricantes", catalogue_id: 6, description: nil},
  {name: "Venta", catalogue_id: 7, description: nil},
  {name: "Traspasos", catalogue_id: 7, description: nil},
  {name: "CCTV", catalogue_id: 8, description: nil},
  {name: "Software", catalogue_id: 6, description: nil},
  {name: "Impresi�_n", catalogue_id: 9, description: nil},
  {name: "Reloj Checador", catalogue_id: 9, description: nil},
  {name: "Implementaci�_n", catalogue_id: 10, description: nil},
  {name: "IT Requests", catalogue_id: 11, description: nil},
  {name: "Servidores", catalogue_id: 9, description: nil},
  {name: "Configuraci�_n", catalogue_id: 10, description: nil},
  {name: "Comunicaciones", catalogue_id: 10, description: nil},
  {name: "Monitoreo", catalogue_id: 12, description: nil},
  {name: "Oracle", catalogue_id: 13, description: nil},
  {name: "Remoto", catalogue_id: 2, description: nil},
  {name: "Agentes", catalogue_id: 14, description: nil},
  {name: "Meta4", catalogue_id: 13, description: nil},
  {name: "Ventas", catalogue_id: 13, description: nil},
  {name: "Portal Proveedores", catalogue_id: 13, description: nil},
  {name: "Future", catalogue_id: 13, description: nil},
  {name: "Facturaci�_n", catalogue_id: 13, description: nil},
  {name: "Epicor", catalogue_id: 13, description: nil},
  {name: "Discoverer", catalogue_id: 13, description: nil},
  {name: "Active Directory", catalogue_id: 15, description: nil},
  {name: "Portal de Accesos", catalogue_id: 15, description: nil},
  {name: "VPN", catalogue_id: 15, description: nil},
  {name: "Compresi�_n de Datos", catalogue_id: 14, description: nil},
  {name: "Executive", catalogue_id: 16, description: nil},
  {name: "Automated Statistics", catalogue_id: 16, description: nil},
  {name: "Historical", catalogue_id: 16, description: nil},
  {name: "Real Time", catalogue_id: 16, description: nil},
  {name: "Create New Team / Subteam", catalogue_id: 18, description: nil},
  {name: "Colaboraci�_n", catalogue_id: 13, description: nil},
  {name: "Internet", catalogue_id: 15, description: nil},
  {name: "C�_digo Telef�_nico", catalogue_id: 15, description: nil},
  {name: "Lotus Notes", catalogue_id: 15, description: nil},
  {name: "Accesorios", catalogue_id: 1, description: nil},
  {name: "Exchange", catalogue_id: 15, description: nil},
  {name: "HR Requests", catalogue_id: 11, description: nil},
  {name: "Proveedores", catalogue_id: 6, description: nil},
  {name: "BLIS", catalogue_id: 15, description: nil},
  {name: "Infraestructura", catalogue_id: 12, description: nil},
  {name: "Red WiFi", catalogue_id: 12, description: nil},
  {name: "Red LAN", catalogue_id: 12, description: nil},
  {name: "Red WAN", catalogue_id: 12, description: nil},
  {name: "Agents", catalogue_id: 19, description: nil},
  {name: "Technical Requirements", catalogue_id: 19, description: nil},
  {name: "Tester", catalogue_id: 19, description: nil},
  {name: "Contracts", catalogue_id: 20, description: nil},
  {name: "Methods", catalogue_id: 20, description: nil},
  {name: "Voz", catalogue_id: 12, description: nil},
  {name: "Desktop", catalogue_id: 9, description: nil},
  {name: "Servicio", catalogue_id: 4, description: nil},
  {name: "Refacciones", catalogue_id: 1, description: nil},
  {name: "No-Break", catalogue_id: 1, description: nil},
  {name: "MPLS Tiendas", catalogue_id: 8, description: nil},
  {name: "Google Chrome", catalogue_id: 2, description: nil},
  {name: "Antivirus", catalogue_id: 2, description: nil},
  {name: "M�_vil", catalogue_id: 21, description: nil},
  {name: "Fija", catalogue_id: 21, description: nil},
  {name: "Intranet", catalogue_id: 8, description: nil},
  {name: "VPN Tiendas", catalogue_id: 8, description: nil},
  {name: "Sistemas Operativos", catalogue_id: 14, description: nil},
  {name: "Navegadores", catalogue_id: 14, description: nil},
  {name: "Monitor", catalogue_id: 1, description: nil},
  {name: "Laptop", catalogue_id: 1, description: nil},
  {name: "Impresoras", catalogue_id: 1, description: nil},
  {name: "SAP", catalogue_id: 2, description: nil},
  {name: "Microsoft Office", catalogue_id: 2, description: nil},
  {name: "Internet Explorer", catalogue_id: 2, description: nil},
  {name: "Documentos", catalogue_id: 14, description: nil},
  {name: "Clientes de Correo", catalogue_id: 14, description: nil},
  {name: "Corte de caja", catalogue_id: 7, description: nil},
  {name: "Oro a cuenta", catalogue_id: 7, description: nil},
  {name: "Pedidos", catalogue_id: 7, description: nil},
  {name: "Teammates", catalogue_id: 18, description: nil},
  {name: "Work Related Activities", catalogue_id: 18, description: nil},
  {name: "Free Days", catalogue_id: 18, description: nil},
  {name: "Inventory", catalogue_id: 18, description: nil},
  {name: "Logs", catalogue_id: 18, description: nil},
  {name: "Teams", catalogue_id: 18, description: nil},
  {name: "Learn Videos", catalogue_id: 22, description: nil},
  {name: "Usuarios", catalogue_id: 23, description: nil},
  {name: "Complains", catalogue_id: 24, description: nil},
  {name: "Suggestions", catalogue_id: 24, description: nil},
  {name: "Success Factor", catalogue_id: 15, description: nil},
  {name: "MP9", catalogue_id: 15, description: nil},
  {name: "Standard", catalogue_id: 14, description: nil},
  {name: "Controladora", catalogue_id: 25, description: nil},
  {name: "Access Point", catalogue_id: 25, description: nil},
  {name: "Cable de Red", catalogue_id: 25, description: nil},
  {name: "Tipos de Equipo", catalogue_id: 23, description: nil},
  {name: "JDE", catalogue_id: 5, description: nil},
  {name: "Tipo de Cliente", catalogue_id: 23, description: nil},
  {name: "Configuraci�_n de Organizaci�_n", catalogue_id: 23, description: nil},
  {name: "Tipos de Contrato", catalogue_id: 23, description: nil},
  {name: "Variables", catalogue_id: 23, description: nil},
  {name: "Servicios �_nicos", catalogue_id: 23, description: nil},
  {name: "Procedimientos", catalogue_id: 23, description: nil},
  {name: "Pr̩stamo de Equipo", catalogue_id: 23, description: nil},
  {name: "Pol�_ticas de Organizaci�_n", catalogue_id: 23, description: nil},
  {name: "Plantillas", catalogue_id: 23, description: nil},
  {name: "Mesas", catalogue_id: 23, description: nil},
  {name: "Checklists", catalogue_id: 23, description: nil},
  {name: "Grupos de Permisos", catalogue_id: 23, description: nil},
  {name: "Grupo de Agentes", catalogue_id: 23, description: nil},
  {name: "Feriados", catalogue_id: 23, description: nil},
  {name: "Distribuci�_n", catalogue_id: 23, description: nil},
  {name: "Configuraci�_n de Acceso Remoto", catalogue_id: 23, description: nil},
  {name: "Cat��logo de Servicio", catalogue_id: 23, description: nil},
  {name: "General", catalogue_id: 23, description: nil},
  {name: "Clientes", catalogue_id: 23, description: nil},
  {name: "Contratos", catalogue_id: 23, description: nil},
  {name: "Informes", catalogue_id: 23, description: nil},
  {name: "Aplicaciones Servidor", catalogue_id: 14, description: nil},
  {name: "Accounts", catalogue_id: 26, description: nil},
  {name: "Company", catalogue_id: 26, description: nil},
  {name: "Administration", catalogue_id: 26, description: nil},
  {name: "Oracle Apps", catalogue_id: 27, description: nil},
  {name: "SOLinux", catalogue_id: 27, description: nil},
  {name: "Ingenier�_a", catalogue_id: 14, description: nil},
  {name: "Portal de Costos", catalogue_id: 13, description: nil},
  {name: "SOWindows", catalogue_id: 27, description: nil},
  {name: "Base de Datos", catalogue_id: 27, description: nil},
  {name: "Lync", catalogue_id: 15, description: nil},
  {name: "FolderCompartido", catalogue_id: 15, description: nil},
  {name: "Telefonia Movil", catalogue_id: 12, description: nil},
  {name: "Aplicaci�_n Oracle", catalogue_id: 14, description: nil},
  {name: "Usuario", catalogue_id: 28, description: nil},
  {name: "Informaci�_n", catalogue_id: 29, description: nil},
  {name: "Metas", catalogue_id: 29, description: nil},
  {name: "Reglas de actividades en computadora", catalogue_id: 29, description: nil},
  {name: "Reglas de actividades sin computadora", catalogue_id: 29, description: nil},
  {name: "Administrador", catalogue_id: 30, description: nil},
  {name: "Gerente", catalogue_id: 30, description: nil},
  {name: "Colegas", catalogue_id: 31, description: nil},
  {name: "Equipos", catalogue_id: 31, description: nil},
  {name: "Actividades relacionadas al trabajo", catalogue_id: 31, description: nil},
  {name: "D�_as Libres", catalogue_id: 31, description: nil},
  {name: "Inventario", catalogue_id: 31, description: nil},
  {name: "Requerimientos T̩cnicos", catalogue_id: 32, description: nil},
  {name: "Mac", catalogue_id: 32, description: nil},
  {name: "Hist�_rico", catalogue_id: 33, description: nil},
  {name: "Ejecutivo", catalogue_id: 33, description: nil},
  {name: "Hoy", catalogue_id: 33, description: nil},
  {name: "Compartir Estad�_sticas", catalogue_id: 33, description: nil},
  {name: "Estad�_sticas Autom��ticas", catalogue_id: 33, description: nil},
  {name: "Funcionalidades", catalogue_id: 34, description: nil},
  {name: "ColaboraTupy", catalogue_id: 15, description: nil},
  {name: "LOLO2", catalogue_id: 35, description: nil},
  {name: "LOLO1", catalogue_id: 35, description: nil},
  {name: "Actividades recurrentes", catalogue_id: 2, description: ""},
  {name: "Account", catalogue_id: 18, description: ""}
])
Item.create!([
  {name: "Disco Duro", area_id: 1, price: nil, description: nil},
  {name: "Puertos USB", area_id: 2, price: nil, description: nil},
  {name: "Mouse", area_id: 2, price: nil, description: nil},
  {name: "Teclado", area_id: 2, price: nil, description: nil},
  {name: "Lentitud", area_id: 3, price: nil, description: nil},
  {name: "MS Office", area_id: 4, price: nil, description: nil},
  {name: "Loop Fabric", area_id: 4, price: nil, description: nil},
  {name: "Antivirus", area_id: 4, price: nil, description: nil},
  {name: "Web Browser", area_id: 4, price: nil, description: nil},
  {name: "Agente", area_id: 4, price: nil, description: nil},
  {name: "Wired", area_id: 5, price: nil, description: nil},
  {name: "Wireless", area_id: 5, price: nil, description: nil},
  {name: "Dedicated Link", area_id: 5, price: nil, description: nil},
  {name: "Firewall", area_id: 5, price: nil, description: nil},
  {name: "Windows", area_id: 6, price: nil, description: nil},
  {name: "eFom", area_id: 6, price: nil, description: nil},
  {name: "Printing", area_id: 6, price: nil, description: nil},
  {name: "Monitor", area_id: 7, price: nil, description: nil},
  {name: "Keyboard", area_id: 7, price: nil, description: nil},
  {name: "HDD", area_id: 7, price: nil, description: nil},
  {name: "Printer", area_id: 7, price: nil, description: nil},
  {name: "Cableado", area_id: 8, price: nil, description: nil},
  {name: "wePresent", area_id: 8, price: nil, description: nil},
  {name: "SalesForce", area_id: 9, price: nil, description: nil},
  {name: "Google Calendar", area_id: 9, price: nil, description: nil},
  {name: "RedBooth", area_id: 9, price: nil, description: nil},
  {name: "Google Drive", area_id: 9, price: nil, description: nil},
  {name: "Google Mail", area_id: 9, price: nil, description: nil},
  {name: "Configuraci�_n", area_id: 3, price: nil, description: nil},
  {name: "Asesoria", area_id: 10, price: nil, description: nil},
  {name: "Instalaci�_n", area_id: 10, price: nil, description: nil},
  {name: "BAM", area_id: 5, price: nil, description: nil},
  {name: "VPN", area_id: 5, price: nil, description: nil},
  {name: "MPLS", area_id: 5, price: nil, description: nil},
  {name: "vmWare", area_id: 11, price: nil, description: nil},
  {name: "JD Edwards", area_id: 6, price: nil, description: nil},
  {name: "Facturaci�_n Eletr�_nica", area_id: 6, price: nil, description: nil},
  {name: "Mobile", area_id: 7, price: nil, description: nil},
  {name: "SERVERS", area_id: 7, price: nil, description: nil},
  {name: "SAN", area_id: 7, price: nil, description: nil},
  {name: "Axtel", area_id: 12, price: nil, description: nil},
  {name: "Telmex", area_id: 12, price: nil, description: nil},
  {name: "Edificio", area_id: 12, price: nil, description: nil},
  {name: "CFE", area_id: 12, price: nil, description: nil},
  {name: "Meraki", area_id: 13, price: nil, description: nil},
  {name: "HP", area_id: 13, price: nil, description: nil},
  {name: "Acer", area_id: 13, price: nil, description: nil},
  {name: "Dell", area_id: 13, price: nil, description: nil},
  {name: "Apple", area_id: 13, price: nil, description: nil},
  {name: "Impresi�_n", area_id: 7, price: nil, description: nil},
  {name: "Escaneo", area_id: 7, price: nil, description: nil},
  {name: "Mantenimiento", area_id: 7, price: nil, description: nil},
  {name: "Falla", area_id: 3, price: nil, description: nil},
  {name: "Precio", area_id: 14, price: nil, description: nil},
  {name: "Promoci�_n", area_id: 14, price: nil, description: nil},
  {name: "Inventario", area_id: 15, price: nil, description: nil},
  {name: "Videos", area_id: 16, price: nil, description: nil},
  {name: "Acceso", area_id: 16, price: nil, description: nil},
  {name: "RDP", area_id: 9, price: nil, description: nil},
  {name: "Router", area_id: 8, price: nil, description: nil},
  {name: "Garant�_a", area_id: 7, price: nil, description: nil},
  {name: "Salesforce", area_id: 17, price: nil, description: nil},
  {name: "Sato", area_id: 18, price: nil, description: nil},
  {name: "No Break", area_id: 7, price: nil, description: nil},
  {name: "MotherBoard", area_id: 7, price: nil, description: nil},
  {name: "Eliminador", area_id: 7, price: nil, description: nil},
  {name: "COI", area_id: 4, price: nil, description: nil},
  {name: "NOI", area_id: 4, price: nil, description: nil},
  {name: "SAE", area_id: 4, price: nil, description: nil},
  {name: "GEMINIS (CHECADOR)", area_id: 4, price: nil, description: nil},
  {name: "Energia", area_id: 19, price: nil, description: nil},
  {name: "Bateria", area_id: 7, price: nil, description: nil},
  {name: "Requerimentos T̩cnicos", area_id: 20, price: nil, description: nil},
  {name: "Permisos de equipo", area_id: 20, price: nil, description: nil},
  {name: "Servicio de Red", area_id: 20, price: nil, description: nil},
  {name: "McOS X", area_id: 10, price: nil, description: nil},
  {name: "Windows 10", area_id: 10, price: nil, description: nil},
  {name: "Windows 8.1", area_id: 10, price: nil, description: nil},
  {name: "Lector", area_id: 19, price: nil, description: nil},
  {name: "Alta de Elemento en Cat��logo", area_id: 21, price: nil, description: nil},
  {name: "Baja de Elemento de Cat��logo", area_id: 21, price: nil, description: nil},
  {name: "WINDOWS", area_id: 4, price: nil, description: nil},
  {name: "Cambio de Elemento de Cat��logo", area_id: 21, price: nil, description: nil},
  {name: "Access Point", area_id: 8, price: nil, description: nil},
  {name: "Proyector", area_id: 2, price: nil, description: nil},
  {name: "Impresora", area_id: 7, price: nil, description: nil},
  {name: "Zebra", area_id: 18, price: nil, description: nil},
  {name: "Servicio", area_id: 19, price: nil, description: nil},
  {name: "Multifuncional", area_id: 18, price: nil, description: nil},
  {name: "Rugger Writer", area_id: 18, price: nil, description: nil},
  {name: "Plotter", area_id: 18, price: nil, description: nil},
  {name: "Storage", area_id: 22, price: nil, description: nil},
  {name: "Windows 8", area_id: 10, price: nil, description: nil},
  {name: "Eficiencias", area_id: 23, price: nil, description: nil},
  {name: "Windows 7", area_id: 10, price: nil, description: nil},
  {name: "Sin conexi�_n", area_id: 24, price: nil, description: nil},
  {name: "Usuario no identificado", area_id: 24, price: nil, description: nil},
  {name: "Equipo sn registrar", area_id: 24, price: nil, description: nil},
  {name: "Actividades Productivas", area_id: 23, price: nil, description: nil},
  {name: "Actividades No Productivas", area_id: 23, price: nil, description: nil},
  {name: "Preguntas Offline", area_id: 23, price: nil, description: nil},
  {name: "Infomes", area_id: 23, price: nil, description: nil},
  {name: "Asignaci�_n de Roles", area_id: 23, price: nil, description: nil},
  {name: "Etiquetadora", area_id: 18, price: nil, description: nil},
  {name: "Solarwinds", area_id: 25, price: nil, description: nil},
  {name: "Ventas SHI", area_id: 26, price: nil, description: nil},
  {name: "Ventas OM", area_id: 26, price: nil, description: nil},
  {name: "SOA / Ventas", area_id: 26, price: nil, description: nil},
  {name: "SOA / Materiales", area_id: 26, price: nil, description: nil},
  {name: "Materiales PUT", area_id: 26, price: nil, description: nil},
  {name: "Materiales Requisiciones", area_id: 26, price: nil, description: nil},
  {name: "Materiales / Quality", area_id: 26, price: nil, description: nil},
  {name: "Materiales Manufcatura", area_id: 26, price: nil, description: nil},
  {name: "ADAMS", area_id: 11, price: nil, description: ""},
  {name: "Materiales Provisionamiento", area_id: 26, price: nil, description: nil},
  {name: "Materiales Inv", area_id: 26, price: nil, description: nil},
  {name: "SOA / Finanzas", area_id: 26, price: nil, description: nil},
  {name: "Materiales Mantenimiento", area_id: 26, price: nil, description: nil},
  {name: "Materiales Pedidos", area_id: 26, price: nil, description: nil},
  {name: "Materiales Inprocurement / Compras", area_id: 26, price: nil, description: nil},
  {name: "Finanzas Informes", area_id: 26, price: nil, description: nil},
  {name: "Finanzas GL", area_id: 26, price: nil, description: nil},
  {name: "Finanzas OIE", area_id: 26, price: nil, description: nil},
  {name: "Finanzas FISO", area_id: 26, price: nil, description: nil},
  {name: "VNC", area_id: 27, price: nil, description: nil},
  {name: "DeskOne", area_id: 28, price: nil, description: nil},
  {name: "Desarrollo", area_id: 29, price: nil, description: nil},
  {name: "Facturaci�_n", area_id: 30, price: nil, description: nil},
  {name: "Informaci�_n", area_id: 19, price: nil, description: nil},
  {name: "Ordenes de Compra", area_id: 31, price: nil, description: nil},
  {name: "Portal", area_id: 31, price: nil, description: nil},
  {name: "Requisiciones", area_id: 31, price: nil, description: nil},
  {name: "Notas de Debito", area_id: 33, price: nil, description: nil},
  {name: "Notas de Credito", area_id: 33, price: nil, description: nil},
  {name: "Facturas", area_id: 33, price: nil, description: nil},
  {name: "Embarques", area_id: 33, price: nil, description: nil},
  {name: "Finanzas Alerta", area_id: 26, price: nil, description: nil},
  {name: "SOA", area_id: 29, price: nil, description: nil},
  {name: "ESS", area_id: 29, price: nil, description: nil},
  {name: "Negocio", area_id: 29, price: nil, description: nil},
  {name: "Nomina", area_id: 29, price: nil, description: nil},
  {name: "Cambio de ubicaci�_n", area_id: 7, price: nil, description: nil},
  {name: "Azurian / ATEB COFIDI", area_id: 33, price: nil, description: nil},
  {name: "E-Mind", area_id: 29, price: nil, description: nil},
  {name: "PeopleNet", area_id: 29, price: nil, description: nil},
  {name: "Microsoft Office", area_id: 9, price: nil, description: nil},
  {name: "Login", area_id: 3, price: nil, description: nil},
  {name: "Escaner", area_id: 7, price: nil, description: nil},
  {name: "Interface", area_id: 35, price: nil, description: nil},
  {name: "Cambio de toner", area_id: 7, price: nil, description: nil},
  {name: "E-mail", area_id: 11, price: nil, description: nil},
  {name: "Work Station", area_id: 7, price: nil, description: nil},
  {name: "Recurso de Red", area_id: 36, price: nil, description: nil},
  {name: "Red", area_id: 36, price: nil, description: nil},
  {name: "Cuenta", area_id: 37, price: nil, description: nil},
  {name: "Homologaci�_n", area_id: 37, price: nil, description: nil},
  {name: "Empresas", area_id: 31, price: nil, description: nil},
  {name: "Finanzas FA", area_id: 26, price: nil, description: nil},
  {name: "Finanzas Aplicaci�_n", area_id: 26, price: nil, description: nil},
  {name: "Finanzas AP", area_id: 26, price: nil, description: nil},
  {name: "Finanzas AR", area_id: 26, price: nil, description: nil},
  {name: "Winzip", area_id: 39, price: nil, description: nil},
  {name: "WinRar", area_id: 39, price: nil, description: nil},
  {name: "TARZip", area_id: 39, price: nil, description: nil},
  {name: "7zip", area_id: 39, price: nil, description: nil},
  {name: "Lync", area_id: 28, price: nil, description: nil},
  {name: "VPN Cisco Client", area_id: 28, price: nil, description: nil},
  {name: "Activities", area_id: 40, price: nil, description: nil},
  {name: "Highlights", area_id: 40, price: nil, description: nil},
  {name: "Password", area_id: 41, price: nil, description: nil},
  {name: "Signup", area_id: 41, price: nil, description: nil},
  {name: "Create", area_id: 42, price: nil, description: nil},
  {name: "Manage", area_id: 42, price: nil, description: nil},
  {name: "Mood", area_id: 40, price: nil, description: nil},
  {name: "Teammates", area_id: 40, price: nil, description: nil},
  {name: "Teams", area_id: 40, price: nil, description: nil},
  {name: "Single Activity (away)", area_id: 40, price: nil, description: nil},
  {name: "Single Activity (computer)", area_id: 40, price: nil, description: nil},
  {name: "Work Goal", area_id: 40, price: nil, description: nil},
  {name: "General / Many Days", area_id: 43, price: nil, description: nil},
  {name: "General / One Day", area_id: 43, price: nil, description: nil},
  {name: "Single Teammate / Many Days", area_id: 43, price: nil, description: nil},
  {name: "Single Teammate / One Day", area_id: 43, price: nil, description: nil},
  {name: "General", area_id: 44, price: nil, description: nil},
  {name: "Details", area_id: 44, price: nil, description: nil},
  {name: "Mood Feature", area_id: 45, price: nil, description: nil},
  {name: "My Stats Feature", area_id: 45, price: nil, description: nil},
  {name: "Question", area_id: 45, price: nil, description: nil},
  {name: "Time Goal", area_id: 45, price: nil, description: nil},
  {name: "QATI", area_id: 26, price: nil, description: nil},
  {name: "LFRS", area_id: 26, price: nil, description: nil},
  {name: "Privilegio", area_id: 47, price: nil, description: nil},
  {name: "C�_digo", area_id: 48, price: nil, description: nil},
  {name: "Cable de energia", area_id: 50, price: nil, description: nil},
  {name: "Lista de Distribucion", area_id: 51, price: nil, description: nil},
  {name: "Cuota", area_id: 51, price: nil, description: nil},
  {name: "Pipedrive", area_id: 17, price: nil, description: nil},
  {name: "Tel̩fono Fijo", area_id: 7, price: nil, description: nil},
  {name: "Cable HDMI", area_id: 8, price: nil, description: nil},
  {name: "Cable Telefonico", area_id: 8, price: nil, description: nil},
  {name: "Banca Electronica", area_id: 9, price: nil, description: nil},
  {name: "Reloj Checador", area_id: 9, price: nil, description: nil},
  {name: "Befective", area_id: 9, price: nil, description: nil},
  {name: "SugarCRM", area_id: 9, price: nil, description: nil},
  {name: "Cable de Red", area_id: 7, price: nil, description: nil},
  {name: "Cable VGA", area_id: 7, price: nil, description: nil},
  {name: "Dockinstation", area_id: 7, price: nil, description: nil},
  {name: "Cambio de Privilegios de Acceso a Red", area_id: 21, price: nil, description: nil},
  {name: "Baja de Usuario", area_id: 52, price: nil, description: nil},
  {name: "Cambio de Usuario", area_id: 52, price: nil, description: nil},
  {name: "Alta de Usuario", area_id: 52, price: nil, description: nil},
  {name: "Solicitud de Servidor", area_id: 21, price: nil, description: nil},
  {name: "Solicitud de Base de Datos", area_id: 21, price: nil, description: nil},
  {name: "Identidad y Acceso", area_id: 21, price: nil, description: nil},
  {name: "Prestamo de Equipo de Computo", area_id: 21, price: nil, description: nil},
  {name: "itManager", area_id: 9, price: nil, description: nil},
  {name: "Privilegios", area_id: 48, price: nil, description: nil},
  {name: "Aire de Precisi�_n", area_id: 55, price: nil, description: nil},
  {name: "Enlace", area_id: 58, price: nil, description: nil},
  {name: "Switch", area_id: 57, price: nil, description: nil},
  {name: "Patch Cord", area_id: 57, price: nil, description: nil},
  {name: "Rack", area_id: 55, price: nil, description: nil},
  {name: "UPS", area_id: 55, price: nil, description: nil},
  {name: "Almacenamiento", area_id: 55, price: nil, description: nil},
  {name: "Cableado de Datos", area_id: 55, price: nil, description: nil},
  {name: "Planta de Energia", area_id: 55, price: nil, description: nil},
  {name: "Gabinete", area_id: 55, price: nil, description: nil},
  {name: "Cableado de Energia", area_id: 55, price: nil, description: nil},
  {name: "Consider Away After", area_id: 45, price: nil, description: nil},
  {name: "Copy Goals and Rules", area_id: 45, price: nil, description: nil},
  {name: "Mac", area_id: 59, price: nil, description: nil},
  {name: "Digital", area_id: 63, price: nil, description: nil},
  {name: "Traditional", area_id: 63, price: nil, description: nil},
  {name: "Cableado de Voz", area_id: 64, price: nil, description: nil},
  {name: "Fuente de Poder", area_id: 65, price: nil, description: nil},
  {name: "Equipo Anal�_gico", area_id: 64, price: nil, description: nil},
  {name: "Prestamo de Cables / Adaptadores de Energ�_a", area_id: 21, price: nil, description: nil},
  {name: "Equipo VoIP", area_id: 64, price: nil, description: nil},
  {name: "Extensi�_n", area_id: 64, price: nil, description: nil},
  {name: "Prestamo de Proyector", area_id: 21, price: nil, description: nil},
  {name: "Prestamo de Monitor", area_id: 21, price: nil, description: nil},
  {name: "AXTEL", area_id: 53, price: nil, description: nil},
  {name: "BBS Red", area_id: 53, price: nil, description: nil},
  {name: "Alestra", area_id: 53, price: nil, description: nil},
  {name: "Ingrammicro", area_id: 53, price: nil, description: nil},
  {name: "Tecsyso", area_id: 53, price: nil, description: nil},
  {name: "Reset de Password", area_id: 66, price: nil, description: nil},
  {name: "Tech-Pro", area_id: 53, price: nil, description: nil},
  {name: "Telcel", area_id: 53, price: nil, description: nil},
  {name: "Nextel", area_id: 53, price: nil, description: nil},
  {name: "Microsoft", area_id: 53, price: nil, description: nil},
  {name: "AVAYA", area_id: 53, price: nil, description: nil},
  {name: "Profitbricks", area_id: 53, price: nil, description: nil},
  {name: "NIC", area_id: 22, price: nil, description: nil},
  {name: "Respaldos de Informaci�_m", area_id: 66, price: nil, description: nil},
  {name: "Cambio de Lugar", area_id: 66, price: nil, description: nil},
  {name: "Java", area_id: 9, price: nil, description: nil},
  {name: "Unidad de Cinta", area_id: 22, price: nil, description: nil},
  {name: "Google Chrome", area_id: 9, price: nil, description: nil},
  {name: "FireFox", area_id: 9, price: nil, description: nil},
  {name: "Internet Explorer", area_id: 9, price: nil, description: nil},
  {name: "ProfitBricks", area_id: 55, price: nil, description: nil},
  {name: "1and1", area_id: 55, price: nil, description: nil},
  {name: "DNS", area_id: 55, price: nil, description: nil},
  {name: "Google Apps", area_id: 55, price: nil, description: nil},
  {name: "Office 365", area_id: 55, price: nil, description: nil},
  {name: "Cisco", area_id: 55, price: nil, description: nil},
  {name: "Tonner", area_id: 50, price: nil, description: nil},
  {name: "Cable de Tel̩fono", area_id: 50, price: nil, description: nil},
  {name: "Pinpad", area_id: 67, price: nil, description: nil},
  {name: "Fuente", area_id: 67, price: nil, description: nil},
  {name: "RAM", area_id: 22, price: nil, description: nil},
  {name: "Memoria RAM", area_id: 67, price: nil, description: nil},
  {name: "Arturito", area_id: 67, price: nil, description: nil},
  {name: "Modem", area_id: 69, price: nil, description: nil},
  {name: "No enciende", area_id: 68, price: nil, description: nil},
  {name: "No respalda", area_id: 68, price: nil, description: nil},
  {name: "Baja", area_id: 72, price: nil, description: nil},
  {name: "Contrataci�_n", area_id: 72, price: nil, description: nil},
  {name: "Aparato", area_id: 72, price: nil, description: nil},
  {name: "Plan de datos", area_id: 72, price: nil, description: nil},
  {name: "Roaming", area_id: 72, price: nil, description: nil},
  {name: "Intermitencia", area_id: 69, price: nil, description: nil},
  {name: "L�_nea directa", area_id: 73, price: nil, description: nil},
  {name: "Extensiones", area_id: 73, price: nil, description: nil},
  {name: "Conmutador", area_id: 73, price: nil, description: nil},
  {name: "Hackeo", area_id: 74, price: nil, description: nil},
  {name: "Cartuchos", area_id: 22, price: nil, description: nil},
  {name: "Array", area_id: 22, price: nil, description: nil},
  {name: "Diadema", area_id: 2, price: nil, description: nil},
  {name: "Microfono", area_id: 2, price: nil, description: nil},
  {name: "HDD Externo", area_id: 2, price: nil, description: nil},
  {name: "Bocinas", area_id: 2, price: nil, description: nil},
  {name: "Enclosure", area_id: 22, price: nil, description: nil},
  {name: "No abre p��gina", area_id: 74, price: nil, description: nil},
  {name: "Modificaci�_n", area_id: 74, price: nil, description: nil},
  {name: "Lento", area_id: 75, price: nil, description: nil},
  {name: "No se carga pieza en SAP", area_id: 15, price: nil, description: nil},
  {name: "No existe pieza", area_id: 15, price: nil, description: nil},
  {name: "No existe pedido en pieza", area_id: 15, price: nil, description: nil},
  {name: "La pieza es para otra sucursal", area_id: 15, price: nil, description: nil},
  {name: "Error de marca y modelo", area_id: 15, price: nil, description: nil},
  {name: "Clonaci�_n", area_id: 28, price: nil, description: nil},
  {name: "Windows XP", area_id: 76, price: nil, description: nil},
  {name: "Firefox", area_id: 77, price: nil, description: nil},
  {name: "Nuevo", area_id: 78, price: nil, description: nil},
  {name: "Falla de colores", area_id: 78, price: nil, description: nil},
  {name: "No permite traspasar", area_id: 15, price: nil, description: nil},
  {name: "Formateo", area_id: 79, price: nil, description: nil},
  {name: "Planchado", area_id: 81, price: nil, description: nil},
  {name: "Transportes", area_id: 81, price: nil, description: nil},
  {name: "Roles", area_id: 81, price: nil, description: nil},
  {name: "Outlook", area_id: 82, price: nil, description: nil},
  {name: "Power Point", area_id: 82, price: nil, description: nil},
  {name: "Excel", area_id: 82, price: nil, description: nil},
  {name: "Word", area_id: 82, price: nil, description: nil},
  {name: "Actualizaci�_n", area_id: 83, price: nil, description: nil},
  {name: "Desinstalaci�_n", area_id: 83, price: nil, description: nil},
  {name: "Safari", area_id: 77, price: nil, description: nil},
  {name: "IE", area_id: 77, price: nil, description: nil},
  {name: "Acrobat", area_id: 84, price: nil, description: nil},
  {name: "Domino NT", area_id: 85, price: nil, description: nil},
  {name: "Respaldo", area_id: 28, price: nil, description: nil},
  {name: "Powerpoint", area_id: 84, price: nil, description: nil},
  {name: "Chrome", area_id: 77, price: nil, description: nil},
  {name: "Office", area_id: 84, price: nil, description: nil},
  {name: "Nota de venta sin datos", area_id: 86, price: nil, description: nil},
  {name: "Cargos pendientes", area_id: 86, price: nil, description: nil},
  {name: "No imprime corte", area_id: 86, price: nil, description: nil},
  {name: "No se env�_a corte", area_id: 86, price: nil, description: nil},
  {name: "No genera corte", area_id: 86, price: nil, description: nil},
  {name: "Error en formas de pago", area_id: 86, price: nil, description: nil},
  {name: "No abre programa", area_id: 87, price: nil, description: nil},
  {name: "No imprime recibo", area_id: 87, price: nil, description: nil},
  {name: "Error en marca y modelo", area_id: 88, price: nil, description: nil},
  {name: "No genera pedido", area_id: 88, price: nil, description: nil},
  {name: "No imprime", area_id: 14, price: nil, description: nil},
  {name: "Archivo da̱ado", area_id: 14, price: nil, description: nil},
  {name: "Error en indice", area_id: 14, price: nil, description: nil},
  {name: "No abre SUIC2", area_id: 14, price: nil, description: nil},
  {name: "Back Up / Restore", area_id: 22, price: nil, description: nil},
  {name: "New Teammates", area_id: 89, price: nil, description: nil},
  {name: "Linux", area_id: 76, price: nil, description: nil},
  {name: "Away Activities", area_id: 45, price: nil, description: nil},
  {name: "Befective Activated", area_id: 45, price: nil, description: nil},
  {name: "Create Free Day", area_id: 91, price: nil, description: nil},
  {name: "Delete Free Day", area_id: 91, price: nil, description: nil},
  {name: "Installed Agents", area_id: 92, price: nil, description: nil},
  {name: "Review", area_id: 93, price: nil, description: nil},
  {name: "Delete Team/Subteam", area_id: 94, price: nil, description: nil},
  {name: "Assign a Team", area_id: 89, price: nil, description: nil},
  {name: "Change Team", area_id: 89, price: nil, description: nil},
  {name: "Ignore Teammate", area_id: 89, price: nil, description: nil},
  {name: "Inactivate Teammate", area_id: 89, price: nil, description: nil},
  {name: "Categories", area_id: 90, price: nil, description: nil},
  {name: "Downloads", area_id: 95, price: nil, description: nil},
  {name: "Alta", area_id: 96, price: nil, description: nil},
  {name: "Statistics", area_id: 95, price: nil, description: nil},
  {name: "Teams & Teammates", area_id: 95, price: nil, description: nil},
  {name: "Your Company", area_id: 95, price: nil, description: nil},
  {name: "Human Service", area_id: 97, price: nil, description: nil},
  {name: "Payment", area_id: 97, price: nil, description: nil},
  {name: "Platform", area_id: 97, price: nil, description: nil},
  {name: "Improvements", area_id: 98, price: nil, description: nil},
  {name: "New Features", area_id: 98, price: nil, description: nil},
  {name: "Trusted Link", area_id: 28, price: nil, description: nil},
  {name: "Otro", area_id: 27, price: nil, description: nil},
  {name: "Discoverer", area_id: 28, price: nil, description: nil},
  {name: "Visio", area_id: 84, price: nil, description: nil},
  {name: "Storage EBS", area_id: 22, price: nil, description: nil},
  {name: "Modificacion Reporte", area_id: 35, price: nil, description: nil},
  {name: "Nuevo Reporte", area_id: 35, price: nil, description: nil},
  {name: "Adobe", area_id: 84, price: nil, description: nil},
  {name: "MINIT AB", area_id: 101, price: nil, description: nil},
  {name: "MS OFFICE", area_id: 101, price: nil, description: nil},
  {name: "MS SQL SERVER", area_id: 101, price: nil, description: nil},
  {name: "CDMON", area_id: 55, price: nil, description: nil},
  {name: "Usuarios", area_id: 102, price: nil, description: nil},
  {name: "SSID", area_id: 103, price: nil, description: nil},
  {name: "Cobertura", area_id: 103, price: nil, description: nil},
  {name: "Cambio", area_id: 104, price: nil, description: nil},
  {name: "Cuentas por Cobrar", area_id: 106, price: nil, description: nil},
  {name: "Cuentas por Pagar", area_id: 106, price: nil, description: nil},
  {name: "Contabilidad General", area_id: 106, price: nil, description: nil},
  {name: "Ventas", area_id: 106, price: nil, description: nil},
  {name: "Compras", area_id: 106, price: nil, description: nil},
  {name: "Uso Horario", area_id: 108, price: nil, description: nil},
  {name: "Moneda", area_id: 108, price: nil, description: nil},
  {name: "Idioma", area_id: 108, price: nil, description: nil},
  {name: "Notificaci�_n de organizaci�_n", area_id: 108, price: nil, description: nil},
  {name: "Usar copyright", area_id: 108, price: nil, description: nil},
  {name: "Usar logo cliente", area_id: 108, price: nil, description: nil},
  {name: "Usar logo itManager", area_id: 108, price: nil, description: nil},
  {name: "Mensaje copyright", area_id: 108, price: nil, description: nil},
  {name: "Organizaci�_n eMail", area_id: 108, price: nil, description: nil},
  {name: "Logo - Busqueda de archivo", area_id: 108, price: nil, description: nil},
  {name: "eMail", area_id: 112, price: nil, description: nil},
  {name: "Modificar Atributo", area_id: 112, price: nil, description: nil},
  {name: "Cambios", area_id: 115, price: nil, description: nil},
  {name: "Pol�_ticas", area_id: 116, price: nil, description: nil},
  {name: "Cat��logos", area_id: 116, price: nil, description: nil},
  {name: "Revisi�_n", area_id: 116, price: nil, description: nil},
  {name: "Etapa", area_id: 116, price: nil, description: nil},
  {name: "Prioridades", area_id: 116, price: nil, description: nil},
  {name: "Estatus", area_id: 116, price: nil, description: nil},
  {name: "Relaciones", area_id: 116, price: nil, description: nil},
  {name: "Campos obligatorios", area_id: 116, price: nil, description: nil},
  {name: "Nuevo Checklist", area_id: 117, price: nil, description: nil},
  {name: "Clientes", area_id: 117, price: nil, description: nil},
  {name: "Editar Campos", area_id: 117, price: nil, description: nil},
  {name: "Tipo", area_id: 117, price: nil, description: nil},
  {name: "Obligatorio", area_id: 117, price: nil, description: nil},
  {name: "Permisos - Administrativo", area_id: 118, price: nil, description: nil},
  {name: "Mother Board", area_id: 65, price: nil, description: nil},
  {name: "CPU", area_id: 65, price: nil, description: nil},
  {name: "Permisos - Gerencia", area_id: 118, price: nil, description: nil},
  {name: "Permisos - Informe", area_id: 118, price: nil, description: nil},
  {name: "Permisos - T̩cnico", area_id: 118, price: nil, description: nil},
  {name: "Permisos - Cliente", area_id: 118, price: nil, description: nil},
  {name: "Grupo de Agentes", area_id: 118, price: nil, description: nil},
  {name: "Informaci�_n General", area_id: 119, price: nil, description: nil},
  {name: "Miembros", area_id: 119, price: nil, description: nil},
  {name: "Expediente", area_id: 119, price: nil, description: nil},
  {name: "Host", area_id: 121, price: nil, description: nil},
  {name: "Host Port", area_id: 121, price: nil, description: nil},
  {name: "SSL", area_id: 121, price: nil, description: nil},
  {name: "Repetidor VNC", area_id: 121, price: nil, description: nil},
  {name: "Seleccione Cliente", area_id: 122, price: nil, description: nil},
  {name: "Seleccione una acci�_n", area_id: 122, price: nil, description: nil},
  {name: "Aplicar a los equipos", area_id: 122, price: nil, description: nil},
  {name: "Asignaci�_n", area_id: 123, price: nil, description: nil},
  {name: "Soluci�_n", area_id: 123, price: nil, description: nil},
  {name: "Asistencia", area_id: 123, price: nil, description: nil},
  {name: "Esfuerzo", area_id: 123, price: nil, description: nil},
  {name: "Grupos de Equipos", area_id: 126, price: nil, description: nil},
  {name: "Distribuci�_n de agentes", area_id: 125, price: nil, description: nil},
  {name: "Adaptador de energia", area_id: 79, price: nil, description: nil},
  {name: "Touch Pad", area_id: 79, price: nil, description: nil},
  {name: "Unidad �_ptica", area_id: 79, price: nil, description: nil},
  {name: "Pantalla", area_id: 79, price: nil, description: nil},
  {name: "Teclado Integrado", area_id: 79, price: nil, description: nil},
  {name: "Puerto HDMI", area_id: 79, price: nil, description: nil},
  {name: "Puerto VGA", area_id: 79, price: nil, description: nil},
  {name: "Consola Antivirus", area_id: 129, price: nil, description: nil},
  {name: "Fuente de Poder Integrada", area_id: 79, price: nil, description: nil},
  {name: "Sharepoint", area_id: 84, price: nil, description: nil},
  {name: "Project", area_id: 84, price: nil, description: nil},
  {name: "SQL", area_id: 129, price: nil, description: nil},
  {name: "Profile", area_id: 130, price: nil, description: nil},
  {name: "Information", area_id: 131, price: nil, description: nil},
  {name: "Goals & Rules", area_id: 131, price: nil, description: nil},
  {name: "Change Rol", area_id: 132, price: nil, description: nil},
  {name: "Delete Admin/Manager", area_id: 132, price: nil, description: nil},
  {name: "Invite Admin/Manager", area_id: 132, price: nil, description: nil},
  {name: "instalaci�_n", area_id: 133, price: nil, description: nil},
  {name: "File Systems", area_id: 134, price: nil, description: nil},
  {name: "Cron Jobs", area_id: 134, price: nil, description: nil},
  {name: "Actualizaciones", area_id: 133, price: nil, description: nil},
  {name: "Reinicio", area_id: 133, price: nil, description: nil},
  {name: "Base de datos", area_id: 100, price: nil, description: nil},
  {name: "Unidad ��ptica", area_id: 65, price: nil, description: nil},
  {name: "Meta4 EMIND", area_id: 28, price: nil, description: nil},
  {name: "Adobe Flash", area_id: 101, price: nil, description: nil},
  {name: "Cisco VPN", area_id: 101, price: nil, description: nil},
  {name: "3D- Data Express", area_id: 135, price: nil, description: nil},
  {name: "Arena-Flow", area_id: 135, price: nil, description: nil},
  {name: "AutoCad", area_id: 135, price: nil, description: nil},
  {name: "Camino Studio", area_id: 135, price: nil, description: nil},
  {name: "CATIA", area_id: 135, price: nil, description: nil},
  {name: "FUTURE", area_id: 135, price: nil, description: nil},
  {name: "MP9", area_id: 135, price: nil, description: nil},
  {name: "PRO-E", area_id: 135, price: nil, description: nil},
  {name: "QGAGES", area_id: 135, price: nil, description: nil},
  {name: "Solid Work", area_id: 135, price: nil, description: nil},
  {name: "Team Mate", area_id: 135, price: nil, description: nil},
  {name: "Respaldos", area_id: 134, price: nil, description: nil},
  {name: "Portal de Costos", area_id: 136, price: nil, description: nil},
  {name: "Creaci�_n de Objetos", area_id: 138, price: nil, description: nil},
  {name: "Reinicio de Procesos", area_id: 137, price: nil, description: nil},
  {name: "Reinstalaci�_n", area_id: 137, price: nil, description: nil},
  {name: "Tareas Programadas", area_id: 137, price: nil, description: nil},
  {name: "Restauraciones", area_id: 134, price: nil, description: nil},
  {name: "ParchCore", area_id: 24, price: nil, description: nil},
  {name: "Admin Cuentas", area_id: 133, price: nil, description: nil},
  {name: "Clonado", area_id: 133, price: nil, description: nil},
  {name: "FailOver", area_id: 133, price: nil, description: nil},
  {name: "Mantenimiento Preventivo", area_id: 138, price: nil, description: nil},
  {name: "Mantenimiento Correctivo", area_id: 138, price: nil, description: nil},
  {name: "Soporte", area_id: 58, price: nil, description: nil},
  {name: "Permisos", area_id: 140, price: nil, description: nil},
  {name: "Enlace MPLS", area_id: 55, price: nil, description: nil},
  {name: "Fibra", area_id: 57, price: nil, description: nil},
  {name: "Carpeta", area_id: 140, price: nil, description: nil},
  {name: "Enlace Respaldo", area_id: 55, price: nil, description: nil},
  {name: "Servidor", area_id: 25, price: nil, description: nil},
  {name: "Clave Llamadas", area_id: 64, price: nil, description: nil},
  {name: "Marcaci�_n Corta", area_id: 64, price: nil, description: nil},
  {name: "Tarjeta de Video", area_id: 65, price: nil, description: nil},
  {name: "Tarjeta de Audio", area_id: 65, price: nil, description: nil},
  {name: "Tarjeta de Red", area_id: 65, price: nil, description: nil},
  {name: "PC-DEMMIS", area_id: 135, price: nil, description: nil},
  {name: "Rendimiento", area_id: 138, price: nil, description: nil},
  {name: "HDD Interno", area_id: 79, price: nil, description: nil},
  {name: "VPN Cisco AnyConnect", area_id: 28, price: nil, description: nil},
  {name: "Dominio", area_id: 129, price: nil, description: nil},
  {name: "Almacenamiento Red", area_id: 76, price: nil, description: nil},
  {name: "Almacenamiento Local", area_id: 76, price: nil, description: nil},
  {name: "Personalizaciones", area_id: 76, price: nil, description: nil},
  {name: "Datos", area_id: 76, price: nil, description: nil},
  {name: "Par��metros de Kernel", area_id: 76, price: nil, description: nil},
  {name: "TrustedLink", area_id: 135, price: nil, description: nil},
  {name: "MAGMA", area_id: 135, price: nil, description: nil},
  {name: "Fluke", area_id: 135, price: nil, description: nil},
  {name: "NX", area_id: 135, price: nil, description: nil},
  {name: "Particiones", area_id: 76, price: nil, description: nil},
  {name: "Procesos", area_id: 76, price: nil, description: nil},
  {name: "Proxy", area_id: 76, price: nil, description: nil},
  {name: "Puertos", area_id: 76, price: nil, description: nil},
  {name: "DataLoad", area_id: 101, price: nil, description: nil},
  {name: "Configuracion", area_id: 141, price: nil, description: nil},
  {name: "Im��genes", area_id: 101, price: nil, description: nil},
  {name: "Cliente Oracle", area_id: 101, price: nil, description: nil},
  {name: "Consola Virtual XP", area_id: 101, price: nil, description: nil},
  {name: "Scripts", area_id: 76, price: nil, description: nil},
  {name: "Perifericos", area_id: 22, price: nil, description: nil},
  {name: "Procesadores", area_id: 22, price: nil, description: nil},
  {name: "DRP", area_id: 138, price: nil, description: nil},
  {name: "Parametros", area_id: 138, price: nil, description: nil},
  {name: "Objetos", area_id: 138, price: nil, description: nil},
  {name: "Reparacion", area_id: 141, price: nil, description: nil},
  {name: "Desarrollos", area_id: 142, price: nil, description: nil},
  {name: "Menus", area_id: 142, price: nil, description: nil},
  {name: "Concurrentes", area_id: 142, price: nil, description: nil},
  {name: "Monitoreo", area_id: 142, price: nil, description: nil},
  {name: "Garantia", area_id: 141, price: nil, description: nil},
  {name: "Nombre", area_id: 143, price: nil, description: nil},
  {name: "Foto", area_id: 143, price: nil, description: nil},
  {name: "Clonados", area_id: 142, price: nil, description: nil},
  {name: "Responsabilidades", area_id: 142, price: nil, description: nil},
  {name: "Zona Horaria", area_id: 143, price: nil, description: nil},
  {name: "Contrase̱a", area_id: 143, price: nil, description: nil},
  {name: "Logo", area_id: 144, price: nil, description: nil},
  {name: "Sitio Web", area_id: 144, price: nil, description: nil},
  {name: "Tel̩fono", area_id: 144, price: nil, description: nil},
  {name: "Tiempo", area_id: 145, price: nil, description: nil},
  {name: "Trabajo", area_id: 145, price: nil, description: nil},
  {name: "Periodo de an��lisis", area_id: 146, price: nil, description: nil},
  {name: "Estad�_sticas personales", area_id: 146, price: nil, description: nil},
  {name: "Pop-up de estado ��nimo", area_id: 146, price: nil, description: nil},
  {name: "L�_mite de tiempo fuera", area_id: 147, price: nil, description: nil},
  {name: "Pop-up de actividades sin computadora", area_id: 147, price: nil, description: nil},
  {name: "Actividades sin computadora", area_id: 147, price: nil, description: nil},
  {name: "Invitaci�_n", area_id: 148, price: nil, description: nil},
  {name: "Eliminaci�_n", area_id: 148, price: nil, description: nil},
  {name: "Rol de Administrador a Gerente", area_id: 148, price: nil, description: nil},
  {name: "Rol de Gerente a Administrador", area_id: 149, price: nil, description: nil},
  {name: "Equipos para gerenciar", area_id: 149, price: nil, description: nil},
  {name: "Creaci�_n", area_id: 150, price: nil, description: nil},
  {name: "Asignaci�_n de primer equipo", area_id: 150, price: nil, description: nil},
  {name: "Cambio de equipo", area_id: 150, price: nil, description: nil},
  {name: "En Espera", area_id: 150, price: nil, description: nil},
  {name: "Ignorados", area_id: 150, price: nil, description: nil},
  {name: "Icono de Befective", area_id: 150, price: nil, description: nil},
  {name: "Pop-up de estado de animo", area_id: 150, price: nil, description: nil},
  {name: "Diferencias entre equipo y sub-equipo", area_id: 151, price: nil, description: nil},
  {name: "Meta de tiempo", area_id: 151, price: nil, description: nil},
  {name: "Reglas de actividades en computadora", area_id: 151, price: nil, description: nil},
  {name: "Reglas de actividades sin computadora", area_id: 151, price: nil, description: nil},
  {name: "Copia de metas y reglas", area_id: 151, price: nil, description: nil},
  {name: "Actividades relacionadas al trabajo", area_id: 151, price: nil, description: nil},
  {name: "Actualizaci�_n de informaci�_n", area_id: 151, price: nil, description: nil},
  {name: "Cambio en la estructura organizacional", area_id: 151, price: nil, description: nil},
  {name: "Categorias en computadora", area_id: 152, price: nil, description: nil},
  {name: "Actividades individuales en computadora", area_id: 152, price: nil, description: nil},
  {name: "Organizacional", area_id: 153, price: nil, description: nil},
  {name: "Equipo", area_id: 153, price: nil, description: nil},
  {name: "Individual", area_id: 153, price: nil, description: nil},
  {name: "Agentes Mac instalados", area_id: 154, price: nil, description: nil},
  {name: "Agentes Windows instalados", area_id: 154, price: nil, description: nil},
  {name: "Acci�_n realizada", area_id: 93, price: nil, description: nil},
  {name: "Elementos modificados", area_id: 93, price: nil, description: nil},
  {name: "Sistema Operativo", area_id: 155, price: nil, description: nil},
  {name: "Conectividad", area_id: 155, price: nil, description: nil},
  {name: "Nombre de Usuario de Colega", area_id: 155, price: nil, description: nil},
  {name: "Comprobador de requisitos de Windows", area_id: 3, price: nil, description: nil},
  {name: "Agente regular", area_id: 3, price: nil, description: nil},
  {name: "M��quina Virtual de Windows", area_id: 3, price: nil, description: nil},
  {name: "General por d�_a", area_id: 157, price: nil, description: nil},
  {name: "Colega por d�_a", area_id: 157, price: nil, description: nil},
  {name: "Colega por horas", area_id: 157, price: nil, description: nil},
  {name: "Colega por hora", area_id: 157, price: nil, description: nil},
  {name: "Resumen", area_id: 158, price: nil, description: nil},
  {name: "Meta de Tiempo", area_id: 158, price: nil, description: nil},
  {name: "Meta de Trabajo", area_id: 158, price: nil, description: nil},
  {name: "Estados de ��nimo", area_id: 158, price: nil, description: nil},
  {name: "Equipos", area_id: 158, price: nil, description: nil},
  {name: "Colegas", area_id: 158, price: nil, description: nil},
  {name: "Actividades", area_id: 158, price: nil, description: nil},
  {name: "Actividad Individual", area_id: 158, price: nil, description: nil},
  {name: "Detalles", area_id: 159, price: nil, description: nil},
  {name: "Email", area_id: 160, price: nil, description: nil},
  {name: "PDF", area_id: 160, price: nil, description: nil},
  {name: "Activaci�_n/Desactivaci�_n", area_id: 161, price: nil, description: nil},
  {name: "Mejora a una existente", area_id: 162, price: nil, description: nil},
  {name: "idea nueva", area_id: 162, price: nil, description: nil},
  {name: "ColaboraTupy LOLO", area_id: 163, price: nil, description: nil},
  {name: "-------", area_id: 164, price: nil, description: nil},
  {name: "LALLA", area_id: 165, price: nil, description: nil},
  {name: "LALA1", area_id: 164, price: nil, description: nil},
  {name: "ADI", area_id: 11, price: nil, description: ""},
  {name: "ACT", area_id: 14, price: nil, description: ""}
])
